import board

"""
This module defines symbolic constants for the stations and connections
between them.
"""

# Stations are defined by a list of pairs:
# - the first component is the station number;
# - the second component is the list of transportation modes for the station,
#   mainly used for display (ferry does not appear on these lists); the list
#   has no duplicates.
# fmt: off
STATIONS : list[tuple[board.StationNumber, list[board.StationKind]]] = [
  (  1, [board.StationKind.BUS,        board.StationKind.TAXI,       board.StationKind.UNDERGROUND]),
  (  2, [board.StationKind.TAXI]),
  (  3, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (  4, [board.StationKind.TAXI]),
  (  5, [board.StationKind.TAXI]),
  (  6, [board.StationKind.TAXI]),
  (  7, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (  8, [board.StationKind.TAXI]),
  (  9, [board.StationKind.TAXI]),
  ( 10, [board.StationKind.TAXI]),
  ( 11, [board.StationKind.TAXI]),
  ( 12, [board.StationKind.TAXI]),
  ( 13, [board.StationKind.BUS,        board.StationKind.TAXI,       board.StationKind.UNDERGROUND]),
  ( 14, [board.StationKind.BUS,        board.StationKind.TAXI]),
  ( 15, [board.StationKind.BUS,        board.StationKind.TAXI]),
  ( 16, [board.StationKind.TAXI]),
  ( 17, [board.StationKind.TAXI]),
  ( 18, [board.StationKind.TAXI]),
  ( 19, [board.StationKind.TAXI]),
  ( 20, [board.StationKind.TAXI]),
  ( 21, [board.StationKind.TAXI]),
  ( 22, [board.StationKind.BUS,        board.StationKind.TAXI]),
  ( 23, [board.StationKind.BUS,        board.StationKind.TAXI]),
  ( 24, [board.StationKind.TAXI]),
  ( 25, [board.StationKind.TAXI]),
  ( 26, [board.StationKind.TAXI]),
  ( 27, [board.StationKind.TAXI]),
  ( 28, [board.StationKind.TAXI]),
  ( 29, [board.StationKind.BUS,        board.StationKind.TAXI]),
  ( 30, [board.StationKind.TAXI]),
  ( 31, [board.StationKind.TAXI]),
  ( 32, [board.StationKind.TAXI]),
  ( 33, [board.StationKind.TAXI]),
  ( 34, [board.StationKind.BUS,        board.StationKind.TAXI]),
  ( 35, [board.StationKind.TAXI]),
  ( 36, [board.StationKind.TAXI]),
  ( 37, [board.StationKind.TAXI]),
  ( 38, [board.StationKind.TAXI]),
  ( 39, [board.StationKind.TAXI]),
  ( 40, [board.StationKind.TAXI]),
  ( 41, [board.StationKind.BUS,        board.StationKind.TAXI]),
  ( 42, [board.StationKind.BUS,        board.StationKind.TAXI]),
  ( 43, [board.StationKind.TAXI]),
  ( 44, [board.StationKind.TAXI]),
  ( 45, [board.StationKind.TAXI]),
  ( 46, [board.StationKind.BUS,        board.StationKind.TAXI,       board.StationKind.UNDERGROUND]),
  ( 47, [board.StationKind.TAXI]),
  ( 48, [board.StationKind.TAXI]),
  ( 49, [board.StationKind.TAXI]),
  ( 50, [board.StationKind.TAXI]),
  ( 51, [board.StationKind.TAXI]),
  ( 52, [board.StationKind.BUS,        board.StationKind.TAXI]),
  ( 53, [board.StationKind.TAXI]),
  ( 54, [board.StationKind.TAXI]),
  ( 55, [board.StationKind.BUS,        board.StationKind.TAXI]),
  ( 56, [board.StationKind.TAXI]),
  ( 57, [board.StationKind.TAXI]),
  ( 58, [board.StationKind.BUS,        board.StationKind.TAXI]),
  ( 59, [board.StationKind.TAXI]),
  ( 60, [board.StationKind.TAXI]),
  ( 61, [board.StationKind.TAXI]),
  ( 62, [board.StationKind.TAXI]),
  ( 63, [board.StationKind.BUS,        board.StationKind.TAXI]),
  ( 64, [board.StationKind.TAXI]),
  ( 65, [board.StationKind.BUS,        board.StationKind.TAXI]),
  ( 66, [board.StationKind.TAXI]),
  ( 67, [board.StationKind.BUS,        board.StationKind.TAXI,       board.StationKind.UNDERGROUND]),
  ( 68, [board.StationKind.TAXI]),
  ( 69, [board.StationKind.TAXI]),
  ( 70, [board.StationKind.TAXI]),
  ( 71, [board.StationKind.TAXI]),
  ( 72, [board.StationKind.BUS,        board.StationKind.TAXI]),
  ( 73, [board.StationKind.TAXI]),
  ( 74, [board.StationKind.BUS,        board.StationKind.TAXI,       board.StationKind.UNDERGROUND]),
  ( 75, [board.StationKind.TAXI]),
  ( 76, [board.StationKind.TAXI]),
  ( 77, [board.StationKind.BUS,        board.StationKind.TAXI]),
  ( 78, [board.StationKind.BUS,        board.StationKind.TAXI]),
  ( 79, [board.StationKind.BUS,        board.StationKind.TAXI,       board.StationKind.UNDERGROUND]),
  ( 80, [board.StationKind.TAXI]),
  ( 81, [board.StationKind.TAXI]),
  ( 82, [board.StationKind.BUS,        board.StationKind.TAXI]),
  ( 83, [board.StationKind.TAXI]),
  ( 84, [board.StationKind.TAXI]),
  ( 85, [board.StationKind.TAXI]),
  ( 86, [board.StationKind.BUS,        board.StationKind.TAXI]),
  ( 87, [board.StationKind.BUS,        board.StationKind.TAXI]),
  ( 88, [board.StationKind.TAXI]),
  ( 89, [board.StationKind.BUS,        board.StationKind.TAXI,       board.StationKind.UNDERGROUND]),
  ( 90, [board.StationKind.TAXI]),
  ( 91, [board.StationKind.TAXI]),
  ( 92, [board.StationKind.TAXI]),
  ( 93, [board.StationKind.BUS,        board.StationKind.TAXI,       board.StationKind.UNDERGROUND]),
  ( 94, [board.StationKind.BUS,        board.StationKind.TAXI]),
  ( 95, [board.StationKind.TAXI]),
  ( 96, [board.StationKind.TAXI]),
  ( 97, [board.StationKind.TAXI]),
  ( 98, [board.StationKind.TAXI]),
  ( 99, [board.StationKind.TAXI]),
  (100, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (101, [board.StationKind.TAXI]),
  (102, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (103, [board.StationKind.TAXI]),
  (104, [board.StationKind.TAXI]),
  (105, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (106, [board.StationKind.TAXI]),
  (107, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (108, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (109, [board.StationKind.TAXI]),
  (110, [board.StationKind.TAXI]),
  (111, [board.StationKind.BUS,        board.StationKind.TAXI,       board.StationKind.UNDERGROUND]),
  (112, [board.StationKind.TAXI]),
  (113, [board.StationKind.TAXI]),
  (114, [board.StationKind.TAXI]),
  (115, [board.StationKind.TAXI]),
  (116, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (117, [board.StationKind.TAXI]),
  (118, [board.StationKind.TAXI]),
  (119, [board.StationKind.TAXI]),
  (120, [board.StationKind.TAXI]),
  (121, [board.StationKind.TAXI]),
  (122, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (123, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (124, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (125, [board.StationKind.TAXI]),
  (126, [board.StationKind.TAXI]),
  (127, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (128, [board.StationKind.BUS,        board.StationKind.TAXI,       board.StationKind.UNDERGROUND]),
  (129, [board.StationKind.TAXI]),
  (130, [board.StationKind.TAXI]),
  (131, [board.StationKind.TAXI]),
  (132, [board.StationKind.TAXI]),
  (133, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (134, [board.StationKind.TAXI]),
  (135, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (136, [board.StationKind.TAXI]),
  (137, [board.StationKind.TAXI]),
  (138, [board.StationKind.TAXI]),
  (139, [board.StationKind.TAXI]),
  (140, [board.StationKind.BUS,        board.StationKind.TAXI,       board.StationKind.UNDERGROUND]),
  (141, [board.StationKind.TAXI]),
  (142, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (143, [board.StationKind.TAXI]),
  (144, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (145, [board.StationKind.TAXI]),
  (146, [board.StationKind.TAXI]),
  (147, [board.StationKind.TAXI]),
  (148, [board.StationKind.TAXI]),
  (149, [board.StationKind.TAXI]),
  (150, [board.StationKind.TAXI]),
  (151, [board.StationKind.TAXI]),
  (152, [board.StationKind.TAXI]),
  (153, [board.StationKind.BUS,        board.StationKind.TAXI,       board.StationKind.UNDERGROUND]),
  (154, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (155, [board.StationKind.TAXI]),
  (156, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (157, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (158, [board.StationKind.TAXI]),
  (159, [board.StationKind.TAXI]),
  (160, [board.StationKind.TAXI]),
  (161, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (162, [board.StationKind.TAXI]),
  (163, [board.StationKind.BUS,        board.StationKind.TAXI,       board.StationKind.UNDERGROUND]),
  (164, [board.StationKind.TAXI]),
  (165, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (166, [board.StationKind.TAXI]),
  (167, [board.StationKind.TAXI]),
  (168, [board.StationKind.TAXI]),
  (169, [board.StationKind.TAXI]),
  (170, [board.StationKind.TAXI]),
  (171, [board.StationKind.TAXI]),
  (172, [board.StationKind.TAXI]),
  (173, [board.StationKind.TAXI]),
  (174, [board.StationKind.TAXI]),
  (175, [board.StationKind.TAXI]),
  (176, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (177, [board.StationKind.TAXI]),
  (178, [board.StationKind.TAXI]),
  (179, [board.StationKind.TAXI]),
  (180, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (181, [board.StationKind.TAXI]),
  (182, [board.StationKind.TAXI]),
  (183, [board.StationKind.TAXI]),
  (184, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (185, [board.StationKind.BUS,        board.StationKind.TAXI,       board.StationKind.UNDERGROUND]),
  (186, [board.StationKind.TAXI]),
  (187, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (188, [board.StationKind.TAXI]),
  (189, [board.StationKind.TAXI]),
  (190, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (191, [board.StationKind.BUS,        board.StationKind.TAXI]),
  (192, [board.StationKind.TAXI]),
  (193, [board.StationKind.TAXI]),
  (194, [board.StationKind.TAXI]),
  (195, [board.StationKind.TAXI]),
  (196, [board.StationKind.TAXI]),
  (197, [board.StationKind.TAXI]),
  (198, [board.StationKind.TAXI]),
  (199, [board.StationKind.BUS,        board.StationKind.TAXI]),
]
# fmt: on

# Connections between stations are defined by a list of triples:
# - the first component is the station number for the source;
# - the second component is the station number for the destination;
# - the third component is the transportation mode associated with the
#   connection.
# fmt: off
CONNECTIONS : list[tuple[board.StationNumber, board.StationNumber, board.ConnectionMode]] = [
  (  1,   8, board.ConnectionMode.TAXI),
  (  1,   9, board.ConnectionMode.TAXI),
  (  1,  46, board.ConnectionMode.BUS),
  (  1,  46, board.ConnectionMode.UNDERGROUND),
  (  1,  58, board.ConnectionMode.BUS),
  (  2,  10, board.ConnectionMode.TAXI),
  (  2,  20, board.ConnectionMode.TAXI),
  (  3,   4, board.ConnectionMode.TAXI),
  (  3,  11, board.ConnectionMode.TAXI),
  (  3,  12, board.ConnectionMode.TAXI),
  (  3,  22, board.ConnectionMode.BUS),
  (  3,  23, board.ConnectionMode.BUS),
  (  4,  13, board.ConnectionMode.TAXI),
  (  5,  15, board.ConnectionMode.TAXI),
  (  5,  16, board.ConnectionMode.TAXI),
  (  6,   7, board.ConnectionMode.TAXI),
  (  6,  29, board.ConnectionMode.TAXI),
  (  7,  17, board.ConnectionMode.TAXI),
  (  7,  42, board.ConnectionMode.BUS),
  (  8,  18, board.ConnectionMode.TAXI),
  (  8,  19, board.ConnectionMode.TAXI),
  (  9,  19, board.ConnectionMode.TAXI),
  (  9,  20, board.ConnectionMode.TAXI),
  ( 10,  11, board.ConnectionMode.TAXI),
  ( 10,  21, board.ConnectionMode.TAXI),
  ( 10,  34, board.ConnectionMode.TAXI),
  ( 11,  22, board.ConnectionMode.TAXI),
  ( 12,  23, board.ConnectionMode.TAXI),
  ( 13,  14, board.ConnectionMode.BUS),
  ( 13,  23, board.ConnectionMode.BUS),
  ( 13,  23, board.ConnectionMode.TAXI),
  ( 13,  24, board.ConnectionMode.TAXI),
  ( 13,  46, board.ConnectionMode.UNDERGROUND),
  ( 13,  52, board.ConnectionMode.BUS),
  ( 13,  67, board.ConnectionMode.UNDERGROUND),
  ( 13,  89, board.ConnectionMode.UNDERGROUND),
  ( 14,  15, board.ConnectionMode.BUS),
  ( 14,  15, board.ConnectionMode.TAXI),
  ( 14,  25, board.ConnectionMode.TAXI),
  ( 15,  16, board.ConnectionMode.TAXI),
  ( 15,  26, board.ConnectionMode.TAXI),
  ( 15,  28, board.ConnectionMode.TAXI),
  ( 15,  29, board.ConnectionMode.BUS),
  ( 15,  41, board.ConnectionMode.BUS),
  ( 16,  28, board.ConnectionMode.TAXI),
  ( 16,  29, board.ConnectionMode.TAXI),
  ( 17,  29, board.ConnectionMode.TAXI),
  ( 17,  30, board.ConnectionMode.TAXI),
  ( 18,  31, board.ConnectionMode.TAXI),
  ( 18,  43, board.ConnectionMode.TAXI),
  ( 19,  32, board.ConnectionMode.TAXI),
  ( 20,  33, board.ConnectionMode.TAXI),
  ( 21,  33, board.ConnectionMode.TAXI),
  ( 22,  23, board.ConnectionMode.BUS),
  ( 22,  23, board.ConnectionMode.TAXI),
  ( 22,  34, board.ConnectionMode.BUS),
  ( 22,  34, board.ConnectionMode.TAXI),
  ( 22,  35, board.ConnectionMode.TAXI),
  ( 22,  65, board.ConnectionMode.BUS),
  ( 23,  37, board.ConnectionMode.TAXI),
  ( 23,  67, board.ConnectionMode.BUS),
  ( 24,  37, board.ConnectionMode.TAXI),
  ( 24,  38, board.ConnectionMode.TAXI),
  ( 25,  38, board.ConnectionMode.TAXI),
  ( 25,  39, board.ConnectionMode.TAXI),
  ( 26,  27, board.ConnectionMode.TAXI),
  ( 26,  39, board.ConnectionMode.TAXI),
  ( 27,  28, board.ConnectionMode.TAXI),
  ( 27,  40, board.ConnectionMode.TAXI),
  ( 28,  41, board.ConnectionMode.TAXI),
  ( 29,  41, board.ConnectionMode.BUS),
  ( 29,  41, board.ConnectionMode.TAXI),
  ( 29,  42, board.ConnectionMode.BUS),
  ( 29,  42, board.ConnectionMode.TAXI),
  ( 29,  55, board.ConnectionMode.BUS),
  ( 30,  42, board.ConnectionMode.TAXI),
  ( 31,  43, board.ConnectionMode.TAXI),
  ( 31,  44, board.ConnectionMode.TAXI),
  ( 32,  33, board.ConnectionMode.TAXI),
  ( 32,  44, board.ConnectionMode.TAXI),
  ( 32,  45, board.ConnectionMode.TAXI),
  ( 33,  46, board.ConnectionMode.TAXI),
  ( 34,  46, board.ConnectionMode.BUS),
  ( 34,  47, board.ConnectionMode.TAXI),
  ( 34,  48, board.ConnectionMode.TAXI),
  ( 34,  63, board.ConnectionMode.BUS),
  ( 35,  36, board.ConnectionMode.TAXI),
  ( 35,  48, board.ConnectionMode.TAXI),
  ( 35,  65, board.ConnectionMode.TAXI),
  ( 36,  37, board.ConnectionMode.TAXI),
  ( 36,  49, board.ConnectionMode.TAXI),
  ( 37,  50, board.ConnectionMode.TAXI),
  ( 38,  50, board.ConnectionMode.TAXI),
  ( 38,  51, board.ConnectionMode.TAXI),
  ( 39,  51, board.ConnectionMode.TAXI),
  ( 39,  52, board.ConnectionMode.TAXI),
  ( 40,  41, board.ConnectionMode.TAXI),
  ( 40,  52, board.ConnectionMode.TAXI),
  ( 40,  53, board.ConnectionMode.TAXI),
  ( 41,  52, board.ConnectionMode.BUS),
  ( 41,  54, board.ConnectionMode.TAXI),
  ( 41,  87, board.ConnectionMode.BUS),
  ( 42,  56, board.ConnectionMode.TAXI),
  ( 42,  72, board.ConnectionMode.BUS),
  ( 42,  72, board.ConnectionMode.TAXI),
  ( 43,  57, board.ConnectionMode.TAXI),
  ( 44,  58, board.ConnectionMode.TAXI),
  ( 45,  46, board.ConnectionMode.TAXI),
  ( 45,  58, board.ConnectionMode.TAXI),
  ( 45,  59, board.ConnectionMode.TAXI),
  ( 45,  60, board.ConnectionMode.TAXI),
  ( 46,  47, board.ConnectionMode.TAXI),
  ( 46,  58, board.ConnectionMode.BUS),
  ( 46,  61, board.ConnectionMode.TAXI),
  ( 46,  74, board.ConnectionMode.UNDERGROUND),
  ( 46,  78, board.ConnectionMode.BUS),
  ( 46,  79, board.ConnectionMode.UNDERGROUND),
  ( 47,  62, board.ConnectionMode.TAXI),
  ( 48,  62, board.ConnectionMode.TAXI),
  ( 48,  63, board.ConnectionMode.TAXI),
  ( 49,  50, board.ConnectionMode.TAXI),
  ( 49,  66, board.ConnectionMode.TAXI),
  ( 51,  52, board.ConnectionMode.TAXI),
  ( 51,  67, board.ConnectionMode.TAXI),
  ( 51,  68, board.ConnectionMode.TAXI),
  ( 52,  67, board.ConnectionMode.BUS),
  ( 52,  69, board.ConnectionMode.TAXI),
  ( 52,  86, board.ConnectionMode.BUS),
  ( 53,  54, board.ConnectionMode.TAXI),
  ( 53,  69, board.ConnectionMode.TAXI),
  ( 54,  55, board.ConnectionMode.TAXI),
  ( 54,  70, board.ConnectionMode.TAXI),
  ( 55,  71, board.ConnectionMode.TAXI),
  ( 55,  89, board.ConnectionMode.BUS),
  ( 56,  91, board.ConnectionMode.TAXI),
  ( 57,  58, board.ConnectionMode.TAXI),
  ( 57,  73, board.ConnectionMode.TAXI),
  ( 58,  59, board.ConnectionMode.TAXI),
  ( 58,  74, board.ConnectionMode.BUS),
  ( 58,  74, board.ConnectionMode.TAXI),
  ( 58,  75, board.ConnectionMode.TAXI),
  ( 58,  77, board.ConnectionMode.BUS),
  ( 59,  75, board.ConnectionMode.TAXI),
  ( 59,  76, board.ConnectionMode.TAXI),
  ( 60,  61, board.ConnectionMode.TAXI),
  ( 60,  76, board.ConnectionMode.TAXI),
  ( 61,  62, board.ConnectionMode.TAXI),
  ( 61,  76, board.ConnectionMode.TAXI),
  ( 61,  78, board.ConnectionMode.TAXI),
  ( 62,  79, board.ConnectionMode.TAXI),
  ( 63,  64, board.ConnectionMode.TAXI),
  ( 63,  65, board.ConnectionMode.BUS),
  ( 63,  79, board.ConnectionMode.BUS),
  ( 63,  79, board.ConnectionMode.TAXI),
  ( 63,  80, board.ConnectionMode.TAXI),
  ( 63, 100, board.ConnectionMode.BUS),
  ( 64,  65, board.ConnectionMode.TAXI),
  ( 64,  81, board.ConnectionMode.TAXI),
  ( 65,  66, board.ConnectionMode.TAXI),
  ( 65,  67, board.ConnectionMode.BUS),
  ( 65,  82, board.ConnectionMode.BUS),
  ( 65,  82, board.ConnectionMode.TAXI),
  ( 66,  67, board.ConnectionMode.TAXI),
  ( 66,  82, board.ConnectionMode.TAXI),
  ( 67,  68, board.ConnectionMode.TAXI),
  ( 67,  79, board.ConnectionMode.UNDERGROUND),
  ( 67,  82, board.ConnectionMode.BUS),
  ( 67,  84, board.ConnectionMode.TAXI),
  ( 67,  89, board.ConnectionMode.UNDERGROUND),
  ( 67, 102, board.ConnectionMode.BUS),
  ( 67, 111, board.ConnectionMode.UNDERGROUND),
  ( 68,  69, board.ConnectionMode.TAXI),
  ( 68,  85, board.ConnectionMode.TAXI),
  ( 69,  86, board.ConnectionMode.TAXI),
  ( 70,  71, board.ConnectionMode.TAXI),
  ( 70,  87, board.ConnectionMode.TAXI),
  ( 71,  72, board.ConnectionMode.TAXI),
  ( 71,  89, board.ConnectionMode.TAXI),
  ( 72,  90, board.ConnectionMode.TAXI),
  ( 72,  91, board.ConnectionMode.TAXI),
  ( 72, 105, board.ConnectionMode.BUS),
  ( 72, 107, board.ConnectionMode.BUS),
  ( 73,  74, board.ConnectionMode.TAXI),
  ( 73,  92, board.ConnectionMode.TAXI),
  ( 74,  75, board.ConnectionMode.TAXI),
  ( 74,  92, board.ConnectionMode.TAXI),
  ( 74,  94, board.ConnectionMode.BUS),
  ( 75,  94, board.ConnectionMode.TAXI),
  ( 76,  77, board.ConnectionMode.TAXI),
  ( 77,  78, board.ConnectionMode.BUS),
  ( 77,  78, board.ConnectionMode.TAXI),
  ( 77,  94, board.ConnectionMode.BUS),
  ( 77,  95, board.ConnectionMode.TAXI),
  ( 77,  96, board.ConnectionMode.TAXI),
  ( 77, 124, board.ConnectionMode.BUS),
  ( 78,  79, board.ConnectionMode.BUS),
  ( 78,  79, board.ConnectionMode.TAXI),
  ( 78,  97, board.ConnectionMode.TAXI),
  ( 79,  93, board.ConnectionMode.UNDERGROUND),
  ( 79,  98, board.ConnectionMode.TAXI),
  ( 79, 111, board.ConnectionMode.UNDERGROUND),
  ( 80,  99, board.ConnectionMode.TAXI),
  ( 80, 100, board.ConnectionMode.TAXI),
  ( 81,  82, board.ConnectionMode.TAXI),
  ( 81, 100, board.ConnectionMode.TAXI),
  ( 82, 100, board.ConnectionMode.BUS),
  ( 82, 101, board.ConnectionMode.TAXI),
  ( 82, 140, board.ConnectionMode.BUS),
  ( 83, 101, board.ConnectionMode.TAXI),
  ( 83, 102, board.ConnectionMode.TAXI),
  ( 84,  85, board.ConnectionMode.TAXI),
  ( 85, 103, board.ConnectionMode.TAXI),
  ( 86,  87, board.ConnectionMode.BUS),
  ( 86, 102, board.ConnectionMode.BUS),
  ( 86, 103, board.ConnectionMode.TAXI),
  ( 86, 104, board.ConnectionMode.TAXI),
  ( 86, 116, board.ConnectionMode.BUS),
  ( 87,  88, board.ConnectionMode.TAXI),
  ( 87, 105, board.ConnectionMode.BUS),
  ( 88,  89, board.ConnectionMode.TAXI),
  ( 88, 117, board.ConnectionMode.TAXI),
  ( 89, 105, board.ConnectionMode.BUS),
  ( 89, 105, board.ConnectionMode.TAXI),
  ( 89, 128, board.ConnectionMode.UNDERGROUND),
  ( 89, 140, board.ConnectionMode.UNDERGROUND),
  ( 90,  91, board.ConnectionMode.TAXI),
  ( 90, 105, board.ConnectionMode.TAXI),
  ( 91, 105, board.ConnectionMode.TAXI),
  ( 91, 107, board.ConnectionMode.TAXI),
  ( 92,  93, board.ConnectionMode.TAXI),
  ( 93,  94, board.ConnectionMode.BUS),
  ( 93,  94, board.ConnectionMode.TAXI),
  ( 94,  95, board.ConnectionMode.TAXI),
  ( 95, 122, board.ConnectionMode.TAXI),
  ( 96,  97, board.ConnectionMode.TAXI),
  ( 96, 109, board.ConnectionMode.TAXI),
  ( 97,  98, board.ConnectionMode.TAXI),
  ( 97, 109, board.ConnectionMode.TAXI),
  ( 98,  99, board.ConnectionMode.TAXI),
  ( 98, 110, board.ConnectionMode.TAXI),
  ( 99, 110, board.ConnectionMode.TAXI),
  ( 99, 112, board.ConnectionMode.TAXI),
  (100, 101, board.ConnectionMode.TAXI),
  (100, 111, board.ConnectionMode.BUS),
  (100, 112, board.ConnectionMode.TAXI),
  (100, 113, board.ConnectionMode.TAXI),
  (101, 114, board.ConnectionMode.TAXI),
  (102, 103, board.ConnectionMode.TAXI),
  (102, 115, board.ConnectionMode.TAXI),
  (102, 127, board.ConnectionMode.BUS),
  (104, 116, board.ConnectionMode.TAXI),
  (105, 106, board.ConnectionMode.TAXI),
  (105, 107, board.ConnectionMode.BUS),
  (105, 108, board.ConnectionMode.BUS),
  (105, 108, board.ConnectionMode.TAXI),
  (106, 107, board.ConnectionMode.TAXI),
  (107, 119, board.ConnectionMode.TAXI),
  (107, 161, board.ConnectionMode.BUS),
  (108, 115, board.ConnectionMode.FERRY),
  (108, 116, board.ConnectionMode.BUS),
  (108, 117, board.ConnectionMode.TAXI),
  (108, 119, board.ConnectionMode.TAXI),
  (108, 135, board.ConnectionMode.BUS),
  (109, 110, board.ConnectionMode.TAXI),
  (109, 124, board.ConnectionMode.TAXI),
  (110, 111, board.ConnectionMode.TAXI),
  (111, 112, board.ConnectionMode.TAXI),
  (111, 124, board.ConnectionMode.BUS),
  (111, 124, board.ConnectionMode.TAXI),
  (111, 153, board.ConnectionMode.UNDERGROUND),
  (111, 163, board.ConnectionMode.UNDERGROUND),
  (112, 125, board.ConnectionMode.TAXI),
  (113, 114, board.ConnectionMode.TAXI),
  (113, 125, board.ConnectionMode.TAXI),
  (114, 115, board.ConnectionMode.TAXI),
  (114, 126, board.ConnectionMode.TAXI),
  (114, 131, board.ConnectionMode.TAXI),
  (114, 132, board.ConnectionMode.TAXI),
  (115, 126, board.ConnectionMode.TAXI),
  (115, 127, board.ConnectionMode.TAXI),
  (115, 157, board.ConnectionMode.FERRY),
  (116, 117, board.ConnectionMode.TAXI),
  (116, 118, board.ConnectionMode.TAXI),
  (116, 127, board.ConnectionMode.BUS),
  (116, 127, board.ConnectionMode.TAXI),
  (116, 142, board.ConnectionMode.BUS),
  (117, 129, board.ConnectionMode.TAXI),
  (118, 129, board.ConnectionMode.TAXI),
  (118, 134, board.ConnectionMode.TAXI),
  (118, 142, board.ConnectionMode.TAXI),
  (119, 136, board.ConnectionMode.TAXI),
  (120, 121, board.ConnectionMode.TAXI),
  (120, 144, board.ConnectionMode.TAXI),
  (121, 122, board.ConnectionMode.TAXI),
  (121, 145, board.ConnectionMode.TAXI),
  (122, 123, board.ConnectionMode.BUS),
  (122, 123, board.ConnectionMode.TAXI),
  (122, 144, board.ConnectionMode.BUS),
  (122, 146, board.ConnectionMode.TAXI),
  (123, 124, board.ConnectionMode.BUS),
  (123, 124, board.ConnectionMode.TAXI),
  (123, 137, board.ConnectionMode.TAXI),
  (123, 144, board.ConnectionMode.BUS),
  (123, 148, board.ConnectionMode.TAXI),
  (123, 149, board.ConnectionMode.TAXI),
  (123, 165, board.ConnectionMode.BUS),
  (124, 130, board.ConnectionMode.TAXI),
  (124, 138, board.ConnectionMode.TAXI),
  (124, 153, board.ConnectionMode.BUS),
  (125, 131, board.ConnectionMode.TAXI),
  (126, 127, board.ConnectionMode.TAXI),
  (126, 140, board.ConnectionMode.TAXI),
  (127, 133, board.ConnectionMode.BUS),
  (127, 133, board.ConnectionMode.TAXI),
  (127, 134, board.ConnectionMode.TAXI),
  (128, 135, board.ConnectionMode.BUS),
  (128, 140, board.ConnectionMode.UNDERGROUND),
  (128, 142, board.ConnectionMode.BUS),
  (128, 142, board.ConnectionMode.TAXI),
  (128, 143, board.ConnectionMode.TAXI),
  (128, 160, board.ConnectionMode.TAXI),
  (128, 161, board.ConnectionMode.BUS),
  (128, 172, board.ConnectionMode.TAXI),
  (128, 185, board.ConnectionMode.UNDERGROUND),
  (128, 187, board.ConnectionMode.BUS),
  (128, 188, board.ConnectionMode.TAXI),
  (128, 199, board.ConnectionMode.BUS),
  (129, 135, board.ConnectionMode.TAXI),
  (129, 142, board.ConnectionMode.TAXI),
  (129, 143, board.ConnectionMode.TAXI),
  (130, 131, board.ConnectionMode.TAXI),
  (130, 139, board.ConnectionMode.TAXI),
  (132, 140, board.ConnectionMode.TAXI),
  (133, 140, board.ConnectionMode.BUS),
  (133, 140, board.ConnectionMode.TAXI),
  (133, 141, board.ConnectionMode.TAXI),
  (133, 157, board.ConnectionMode.BUS),
  (134, 141, board.ConnectionMode.TAXI),
  (134, 142, board.ConnectionMode.TAXI),
  (135, 136, board.ConnectionMode.TAXI),
  (135, 143, board.ConnectionMode.TAXI),
  (135, 161, board.ConnectionMode.BUS),
  (135, 161, board.ConnectionMode.TAXI),
  (136, 162, board.ConnectionMode.TAXI),
  (137, 147, board.ConnectionMode.TAXI),
  (138, 150, board.ConnectionMode.TAXI),
  (138, 152, board.ConnectionMode.TAXI),
  (139, 140, board.ConnectionMode.TAXI),
  (139, 153, board.ConnectionMode.TAXI),
  (139, 154, board.ConnectionMode.TAXI),
  (140, 153, board.ConnectionMode.UNDERGROUND),
  (140, 154, board.ConnectionMode.BUS),
  (140, 154, board.ConnectionMode.TAXI),
  (140, 156, board.ConnectionMode.BUS),
  (140, 156, board.ConnectionMode.TAXI),
  (141, 142, board.ConnectionMode.TAXI),
  (141, 158, board.ConnectionMode.TAXI),
  (142, 143, board.ConnectionMode.TAXI),
  (142, 157, board.ConnectionMode.BUS),
  (142, 158, board.ConnectionMode.TAXI),
  (143, 160, board.ConnectionMode.TAXI),
  (144, 145, board.ConnectionMode.TAXI),
  (144, 163, board.ConnectionMode.BUS),
  (144, 177, board.ConnectionMode.TAXI),
  (145, 146, board.ConnectionMode.TAXI),
  (146, 147, board.ConnectionMode.TAXI),
  (146, 163, board.ConnectionMode.TAXI),
  (147, 164, board.ConnectionMode.TAXI),
  (148, 149, board.ConnectionMode.TAXI),
  (148, 164, board.ConnectionMode.TAXI),
  (149, 150, board.ConnectionMode.TAXI),
  (149, 165, board.ConnectionMode.TAXI),
  (150, 151, board.ConnectionMode.TAXI),
  (151, 152, board.ConnectionMode.TAXI),
  (151, 165, board.ConnectionMode.TAXI),
  (151, 166, board.ConnectionMode.TAXI),
  (152, 153, board.ConnectionMode.TAXI),
  (153, 154, board.ConnectionMode.BUS),
  (153, 154, board.ConnectionMode.TAXI),
  (153, 163, board.ConnectionMode.UNDERGROUND),
  (153, 166, board.ConnectionMode.TAXI),
  (153, 167, board.ConnectionMode.TAXI),
  (153, 180, board.ConnectionMode.BUS),
  (153, 184, board.ConnectionMode.BUS),
  (153, 185, board.ConnectionMode.UNDERGROUND),
  (154, 155, board.ConnectionMode.TAXI),
  (154, 156, board.ConnectionMode.BUS),
  (155, 156, board.ConnectionMode.TAXI),
  (155, 167, board.ConnectionMode.TAXI),
  (155, 168, board.ConnectionMode.TAXI),
  (156, 157, board.ConnectionMode.BUS),
  (156, 157, board.ConnectionMode.TAXI),
  (156, 169, board.ConnectionMode.TAXI),
  (156, 184, board.ConnectionMode.BUS),
  (157, 158, board.ConnectionMode.TAXI),
  (157, 170, board.ConnectionMode.TAXI),
  (157, 185, board.ConnectionMode.BUS),
  (157, 194, board.ConnectionMode.FERRY),
  (158, 159, board.ConnectionMode.TAXI),
  (159, 170, board.ConnectionMode.TAXI),
  (159, 172, board.ConnectionMode.TAXI),
  (159, 186, board.ConnectionMode.TAXI),
  (159, 198, board.ConnectionMode.TAXI),
  (160, 161, board.ConnectionMode.TAXI),
  (160, 173, board.ConnectionMode.TAXI),
  (161, 174, board.ConnectionMode.TAXI),
  (161, 199, board.ConnectionMode.BUS),
  (162, 175, board.ConnectionMode.TAXI),
  (163, 176, board.ConnectionMode.BUS),
  (163, 177, board.ConnectionMode.TAXI),
  (163, 191, board.ConnectionMode.BUS),
  (164, 178, board.ConnectionMode.TAXI),
  (164, 179, board.ConnectionMode.TAXI),
  (165, 179, board.ConnectionMode.TAXI),
  (165, 180, board.ConnectionMode.BUS),
  (165, 180, board.ConnectionMode.TAXI),
  (165, 191, board.ConnectionMode.BUS),
  (166, 181, board.ConnectionMode.TAXI),
  (166, 183, board.ConnectionMode.TAXI),
  (167, 168, board.ConnectionMode.TAXI),
  (167, 183, board.ConnectionMode.TAXI),
  (168, 184, board.ConnectionMode.TAXI),
  (169, 184, board.ConnectionMode.TAXI),
  (170, 185, board.ConnectionMode.TAXI),
  (171, 173, board.ConnectionMode.TAXI),
  (171, 175, board.ConnectionMode.TAXI),
  (171, 199, board.ConnectionMode.TAXI),
  (172, 187, board.ConnectionMode.TAXI),
  (173, 174, board.ConnectionMode.TAXI),
  (173, 188, board.ConnectionMode.TAXI),
  (174, 175, board.ConnectionMode.TAXI),
  (176, 177, board.ConnectionMode.TAXI),
  (176, 189, board.ConnectionMode.TAXI),
  (176, 190, board.ConnectionMode.BUS),
  (178, 189, board.ConnectionMode.TAXI),
  (178, 191, board.ConnectionMode.TAXI),
  (179, 191, board.ConnectionMode.TAXI),
  (180, 181, board.ConnectionMode.TAXI),
  (180, 184, board.ConnectionMode.BUS),
  (180, 190, board.ConnectionMode.BUS),
  (180, 193, board.ConnectionMode.TAXI),
  (181, 182, board.ConnectionMode.TAXI),
  (181, 193, board.ConnectionMode.TAXI),
  (182, 183, board.ConnectionMode.TAXI),
  (182, 195, board.ConnectionMode.TAXI),
  (183, 196, board.ConnectionMode.TAXI),
  (184, 185, board.ConnectionMode.BUS),
  (184, 185, board.ConnectionMode.TAXI),
  (184, 196, board.ConnectionMode.TAXI),
  (184, 197, board.ConnectionMode.TAXI),
  (185, 186, board.ConnectionMode.TAXI),
  (185, 187, board.ConnectionMode.BUS),
  (186, 198, board.ConnectionMode.TAXI),
  (187, 188, board.ConnectionMode.TAXI),
  (187, 198, board.ConnectionMode.TAXI),
  (188, 199, board.ConnectionMode.TAXI),
  (189, 190, board.ConnectionMode.TAXI),
  (190, 191, board.ConnectionMode.BUS),
  (190, 191, board.ConnectionMode.TAXI),
  (190, 192, board.ConnectionMode.TAXI),
  (191, 192, board.ConnectionMode.TAXI),
  (192, 194, board.ConnectionMode.TAXI),
  (193, 194, board.ConnectionMode.TAXI),
  (194, 195, board.ConnectionMode.TAXI),
  (195, 197, board.ConnectionMode.TAXI),
  (196, 197, board.ConnectionMode.TAXI),
  (198, 199, board.ConnectionMode.TAXI),
]
# fmt: on
